// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Terminarz_siłownia.Baza_danych.Context;

namespace Terminarz_siłownia.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    partial class DataBaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Terminarz_siłownia.Baza_danych.Model.Cwiczenie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCwiczenia")
                        .HasColumnType("TEXT");

                    b.Property<int>("IloscPowtorzen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KategoriaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OsobaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KategoriaId");

                    b.HasIndex("OsobaId");

                    b.ToTable("Cwiczenia");
                });

            modelBuilder.Entity("Terminarz_siłownia.Baza_danych.Model.Kategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NazwaKategorii")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategorie");
                });

            modelBuilder.Entity("Terminarz_siłownia.Baza_danych.Model.Osoba", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Imie_Nazwisko")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Osoby");
                });

            modelBuilder.Entity("Terminarz_siłownia.Baza_danych.Model.Cwiczenie", b =>
                {
                    b.HasOne("Terminarz_siłownia.Baza_danych.Model.Kategoria", "Kategoria")
                        .WithMany()
                        .HasForeignKey("KategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Terminarz_siłownia.Baza_danych.Model.Osoba", "Osoba")
                        .WithMany()
                        .HasForeignKey("OsobaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
