// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Przelicznik.BazaDanych.Context;

namespace Przelicznik.BazaDanych.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20220323131322_pierwsza migracja")]
    partial class pierwszamigracja
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("Przelicznik.BazaDanych.Model.Jednostki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.Property<int>("RodzajId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RodzajId");

                    b.ToTable("Jednostki");
                });

            modelBuilder.Entity("Przelicznik.BazaDanych.Model.Przeliczniki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JednostkaDocelowaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JednostkaZrodlowaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JednostkaDocelowaId");

                    b.HasIndex("JednostkaZrodlowaId");

                    b.ToTable("Przeliczniki");
                });

            modelBuilder.Entity("Przelicznik.BazaDanych.Model.Rodzaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rodzaj");
                });

            modelBuilder.Entity("Przelicznik.BazaDanych.Model.Jednostki", b =>
                {
                    b.HasOne("Przelicznik.BazaDanych.Model.Rodzaj", "Rodzaj")
                        .WithMany()
                        .HasForeignKey("RodzajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Przelicznik.BazaDanych.Model.Przeliczniki", b =>
                {
                    b.HasOne("Przelicznik.BazaDanych.Model.Jednostki", "JednostkaDocelowa")
                        .WithMany()
                        .HasForeignKey("JednostkaDocelowaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Przelicznik.BazaDanych.Model.Jednostki", "JednostkaZrodlowa")
                        .WithMany()
                        .HasForeignKey("JednostkaZrodlowaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
